package server.utils;

/**
 * TODO fazer o registo e login para ficheiros, utilizar o shared object "UserTracking"
 */
public class MiddleClientLoginProtocol {
    private static enum MainStates {
        CHECK_LOGIN /** handle login communication with client */, 
        REGISTER_CLIENT/** handle registration communication with client */, LOGGED
    };

    private static enum SecStates {
        NOT_DEFINED, GET_NAME /** request Client a locationName */, GET_PASSWORD /** request Client the password */, 
        RETYPE_PASSWORD /** registration password confirmation */, 
        GET_SERVER_DATA /** request Server if the Client is already logged in (other locations) */
    };

    private MainStates main_state = MainStates.CHECK_LOGIN;
    private SecStates sec_state = SecStates.NOT_DEFINED;

    private String locationName; /** Location name of the Client that's logging in */
    private String password; /** Location password for verification */
    private String multicastIP; /** Client respective multicastIP, generated by server using this protocol */
    private int multicastPort; /** Client respective multicastPort, generated by server using this protocol */
    private boolean dummy = false;

    private ClientConnectionTracking shared;

    public MiddleClientLoginProtocol(ClientConnectionTracking shared) {
        this.shared = shared;
    }

    public String processInput(String theInput) {
        String theOutput = null;

        // Check special inputs
        if (theInput.equals("%register")) {
            main_state = MainStates.REGISTER_CLIENT;
            sec_state = SecStates.GET_NAME;
        } else if (theInput.equals("%cancel")) {
            main_state = MainStates.CHECK_LOGIN;
            sec_state = SecStates.NOT_DEFINED;
        }

        /**
         * TODO guardar nome da localização, multicast ip e porta durante o processar do protocolo
         * NOTA: o ip e porta do multicast vao ser gerados automaticamente aqui ou no ClientConnectionTracking.
         *      Quando forem gerados devem ser guardados em variaveis neste protocolo para possibilitar os metodos "get"
         */

        if (main_state == MainStates.CHECK_LOGIN) {
            if (sec_state == SecStates.GET_NAME) {
                if (!theInput.isEmpty()) {
                    theOutput = "Invalid Location! Enter Location name.";
                } else if (/* theInput does not exist in registered users */dummy) {
                    theOutput = "Location is not registered, want to register? Type %register, or enter a new name.";
                } else {
                    // User exists
                    locationName = theInput;
                    theOutput = "Enter the password.";
                    sec_state = SecStates.GET_PASSWORD;
                }
            } else if (sec_state == SecStates.GET_PASSWORD) {
                if (/* password incorrect */dummy) {
                    theOutput = "Password is incorrect. Retype password or write %cancel to change Location name.";
                } else {
                    theOutput = "findUserLogin:" + locationName;
                    sec_state = SecStates.GET_SERVER_DATA;
                }
            } else if (sec_state == SecStates.GET_SERVER_DATA) {
                if (theInput.startsWith("true")) {
                    /** User has a login in another location */
                    theOutput = "You are already logged-in in " + theInput.substring(theInput.indexOf(",", 0))
                                    + ". Please logout or try another account.";
                    sec_state = SecStates.GET_NAME;
                } else {

                    /**
                     * TODO Login User (adicionar user a um objeto partilhado entre threads, com os clientes de login efetuado)
                     */

                    theOutput = "logged-in"; // key-word for sinalizing login in communication thread
                    main_state = MainStates.LOGGED;
                }
            } else {
                theOutput = "Greetings from the Main Server! Enter your Location name. (To register a new Location type %register!)";
                sec_state = SecStates.GET_PASSWORD;
            }

        } else if (main_state == MainStates.REGISTER_CLIENT) {
            if (sec_state == SecStates.GET_NAME) {
                if (theInput.length() < 3 && theInput.length() > 30) {
                    theOutput = "Location name must be within 3 and 30 characters. Enter a new name.";
                } else if (/* theInput exists in registered users */dummy) {
                    theOutput = "Location already exists. Write a new name or %cancel to go back to Login!";
                } else {
                    // User is new
                    theOutput = "Enter Location password.";
                    sec_state = SecStates.GET_PASSWORD;
                }
            } else if (sec_state == SecStates.GET_PASSWORD) {
                if (theInput.length() < 4 && theInput.length() > 16) {
                    theOutput = "Password must be within 4 and 16 characters. Retype password or write %cancel to change locationName.";
                } else {
                    /*
                    Pode-se aproveitar para enviar uma mensagem a avisar o User se a password é fraca, etc. aqui.
                    */
                    theOutput = "Nice password! Please, retype it for verification.";
                    password = theInput; // Store password to check with the retype
                    sec_state = SecStates.RETYPE_PASSWORD;
                }
            } else if (sec_state == SecStates.RETYPE_PASSWORD) {
                if (!password.equals(theInput)) {
                    theOutput = "Passwords do not match, restart registration. Enter a Location Name. (Type %cancel to go back to Login page!)";
                    sec_state = SecStates.GET_NAME;
                    password = "";
                } else {

                    /** 
                     * TODO Register Client (adicionar localização à base de dados de ficheiros)
                     */

                    main_state = MainStates.CHECK_LOGIN;
                }
            } else {
                theOutput = "Welcome to the Registration Page! Enter a Location name. (To go back to Login page type %cancel!)";
                sec_state = SecStates.GET_NAME;
            }

        } else {
            // main_state == MainStates.LOGGED
            theOutput = "Client Logged-In successfully into Main Server!";
        }
        return theOutput;
    }

    public String getLocationName() {
        return this.locationName;
    }

    public String getMulticastIP() {
        return this.multicastIP;
    }

    public int getMulticastPort() {
        return this.multicastPort;
    }
}